apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-instance
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bart-kus/awx-gitops-repo.git'
    targetRevision: HEAD
    path: awx
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: awx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
